trigger:
  - master

pr: none

pool:
  name: Hosted Ubuntu 1604

steps:
  - task: npmAuthenticate@0
    displayName: "npm Authenticate .npmrc"
    inputs:
      workingFile: .npmrc

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      containerRegistry: 'ACR Connection'
      repository: $(Build.Repository.Name)
      command: 'build'
      Dockerfile: '**/Dockerfile'
      buildContext: '**'
      tags: |
        $(Build.BuildId)
        latest
      arguments: '--build-arg NPM_TOKEN=$(NPM_TOKEN)'

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      containerRegistry: 'ACR Connection'
      repository: $(Build.Repository.Name)
      command: 'push'
      tags: |
            $(Build.BuildId)
            latest

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: .helm
